CREATE TABLE carros (
    id INT AUTO_INCREMENT PRIMARY KEY,
    continente VARCHAR(50) NOT NULL,
    pais VARCHAR(50) NOT NULL,
    marca VARCHAR(50) NOT NULL,
    modelo VARCHAR(100) NOT NULL
);

INSERT INTO carros (continente, pais, marca, modelo) VALUES
-- ALEMANHA
('EUROPA', 'ALEMANHA', 'Audi', 'A1'),
('EUROPA', 'ALEMANHA', 'Audi', 'A3'),
('EUROPA', 'ALEMANHA', 'Audi', 'A4'),
('EUROPA', 'ALEMANHA', 'Audi', 'A5'),
('EUROPA', 'ALEMANHA', 'Audi', 'A6'),
('EUROPA', 'ALEMANHA', 'Audi', 'A7'),
('EUROPA', 'ALEMANHA', 'Audi', 'A8'),
('EUROPA', 'ALEMANHA', 'Audi', 'Q2'),
('EUROPA', 'ALEMANHA', 'Audi', 'Q3'),
('EUROPA', 'ALEMANHA', 'Audi', 'Q4 e-tron'),
('EUROPA', 'ALEMANHA', 'Audi', 'Q5'),
('EUROPA', 'ALEMANHA', 'Audi', 'Q6 e-tron'),
('EUROPA', 'ALEMANHA', 'Audi', 'Q7'),
('EUROPA', 'ALEMANHA', 'Audi', 'Q8'),
('EUROPA', 'ALEMANHA', 'Audi', 'e-tron GT'),
('EUROPA', 'ALEMANHA', 'Audi', 'R8'),
('EUROPA', 'ALEMANHA', 'BMW', 'Isetta'),
('EUROPA', 'ALEMANHA', 'BMW', 'Série 1'),
('EUROPA', 'ALEMANHA', 'BMW', 'Série 2'),
('EUROPA', 'ALEMANHA', 'BMW', 'Série 3'),
('EUROPA', 'ALEMANHA', 'BMW', 'Série 4'),
('EUROPA', 'ALEMANHA', 'BMW', 'Série 5'),
('EUROPA', 'ALEMANHA', 'BMW', 'Série 7'),
('EUROPA', 'ALEMANHA', 'BMW', 'Série 8'),
('EUROPA', 'ALEMANHA', 'BMW', 'i4'),
('EUROPA', 'ALEMANHA', 'BMW', 'i5'),
('EUROPA', 'ALEMANHA', 'BMW', 'i7'),
('EUROPA', 'ALEMANHA', 'BMW', 'iX'),
('EUROPA', 'ALEMANHA', 'BMW', 'iX1'),
('EUROPA', 'ALEMANHA', 'BMW', 'iX2'),
('EUROPA', 'ALEMANHA', 'BMW', 'iX3'),
('EUROPA', 'ALEMANHA', 'BMW', 'X1'),
('EUROPA', 'ALEMANHA', 'BMW', 'X3'),
('EUROPA', 'ALEMANHA', 'BMW', 'X5'),
('EUROPA', 'ALEMANHA', 'BMW', 'XM'),
('EUROPA', 'ALEMANHA', 'BMW', 'Z4'),
('EUROPA', 'ALEMANHA', 'BMW', 'M2'),
('EUROPA', 'ALEMANHA', 'BMW', 'M3'),
('EUROPA', 'ALEMANHA', 'BMW', 'M4'),
('EUROPA', 'ALEMANHA', 'BMW', 'M5'),
('EUROPA', 'ALEMANHA', 'BMW', 'M8'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe A'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe B'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe C'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe E'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe S'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe T'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe V'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'GLA'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'GLB'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'GLC'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'GLE'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'GLS'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'Classe G'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'EQA'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'EQB'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'EQC'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'EQE'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'EQS'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'EQT'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'EQV'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'CLA'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'CLE'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'AMG GT'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'AMG SL'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'MayBach Classe S'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'MayBach EQS'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'MayBach GLS'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'MayBach SL'),
('EUROPA', 'ALEMANHA', 'Mercedes-Benz', 'SLR McLaren'),
('EUROPA', 'ALEMANHA', 'Volkswagen', 'Golf'),
('EUROPA', 'ALEMANHA', 'Volkswagen', 'ID.3'),
('EUROPA', 'ALEMANHA', 'Volkswagen', 'ID.4'),
('EUROPA', 'ALEMANHA', 'Volkswagen', 'ID.5'),
('EUROPA', 'ALEMANHA', 'Volkswagen', 'Tiguan'),
('EUROPA', 'ALEMANHA', 'Volkswagen', 'Passat'),
('EUROPA', 'ALEMANHA', 'Porsche', 'Taycan'),
('EUROPA', 'ALEMANHA', 'Porsche', 'Panamera'),
('EUROPA', 'ALEMANHA', 'Porsche', '911'),
('EUROPA', 'ALEMANHA', 'Porsche', '718'),
('EUROPA', 'ALEMANHA', 'Porsche', 'Cayenne'),
('EUROPA', 'ALEMANHA', 'Porsche', 'Macan'),
('EUROPA', 'ALEMANHA', 'Opel', 'Astra'),
('EUROPA', 'ALEMANHA', 'Opel', 'Corsa'),
('EUROPA', 'ALEMANHA', 'Opel', 'Mokka'),
('EUROPA', 'ALEMANHA', 'Opel', 'Grandland'),
('EUROPA', 'ALEMANHA', 'Smart', '#1'),
('EUROPA', 'ALEMANHA', 'Smart', '#3'),

-- ITÁLIA
('EUROPA', 'ITÁLIA', 'Fiat', '500e'),
('EUROPA', 'ITÁLIA', 'Fiat', 'Tipo'),
('EUROPA', 'ITÁLIA', 'Fiat', '600e'),
('EUROPA', 'ITÁLIA', 'Alfa Romeo', 'Tonale'),
('EUROPA', 'ITÁLIA', 'Alfa Romeo', 'Giulia'),
('EUROPA', 'ITÁLIA', 'Alfa Romeo', 'Stelvio'),
('EUROPA', 'ITÁLIA', 'Maserati', 'Grecale'),
('EUROPA', 'ITÁLIA', 'Maserati', 'Grancabrio'),
('EUROPA', 'ITÁLIA', 'Maserati', 'MCPura'),
('EUROPA', 'ITÁLIA', 'Maserati', 'MC20'),
('EUROPA', 'ITÁLIA', 'Maserati', 'GranTurismo'),
('EUROPA', 'ITÁLIA', 'Maserati', 'GT2'),
('EUROPA', 'ITÁLIA', 'Maserati', 'MCXtrema'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'Roma'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'SF90'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'Purosangue'),
('EUROPA', 'ITÁLIA', 'Ferrari', '296 GTB'),
('EUROPA', 'ITÁLIA', 'Ferrari', '12cilindri'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'Daytona SP3'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'Amalfi'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'F12berlinetta'),
('EUROPA', 'ITÁLIA', 'Ferrari', '812'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'GTC4Lusso'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'California'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'Portofino'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'Testarossa'),
('EUROPA', 'ITÁLIA', 'Ferrari', '360'),
('EUROPA', 'ITÁLIA', 'Ferrari', '488'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'F8'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'Monza SP1'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'Monza SP2'),
('EUROPA', 'ITÁLIA', 'Ferrari', '288 GTO'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'F40'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'F50'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'Enzo'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'LaFerrari'),
('EUROPA', 'ITÁLIA', 'Ferrari', 'F80'),
('EUROPA', 'ITÁLIA', 'Lamborghini', 'Revuelto'),
('EUROPA', 'ITÁLIA', 'Lamborghini', 'Huracán'),
('EUROPA', 'ITÁLIA', 'Lamborghini', 'Urus'),
('EUROPA', 'ITÁLIA', 'Lamborghini', 'Aventador'),
('EUROPA', 'ITÁLIA', 'Lamborghini', 'Countach'),
('EUROPA', 'ITÁLIA', 'Lamborghini', 'Temerario'),
('EUROPA', 'ITÁLIA', 'Lamborghini', 'Miura'),
('EUROPA', 'ITÁLIA', 'Lamborghini', 'Diablo'),
('EUROPA', 'ITÁLIA', 'Lamborghini', 'Murciélago'),
('EUROPA', 'ITÁLIA', 'Lamborghini', 'Gallardo'),
('EUROPA', 'ITÁLIA', 'Pagani', 'Utopia'),
('EUROPA', 'ITÁLIA', 'Pagani', 'Huayra R'),
('EUROPA', 'ITÁLIA', 'Bugatti', 'Veyron'),
('EUROPA', 'ITÁLIA', 'Bugatti', 'Chiron'),
('EUROPA', 'ITÁLIA', 'Bugatti', 'Mistral'),
('EUROPA', 'ITÁLIA', 'Bugatti', 'Tourbillon'),

-- FRANÇA
('EUROPA', 'FRANÇA', 'Renault', 'Clio'),
('EUROPA', 'FRANÇA', 'Renault', 'Captur'),
('EUROPA', 'FRANÇA', 'Renault', 'Arkana'),
('EUROPA', 'FRANÇA', 'Renault', 'Megane E-Tech'),
('EUROPA', 'FRANÇA', 'Renault', 'Austral'),
('EUROPA', 'FRANÇA', 'Peugeot', '208'),
('EUROPA', 'FRANÇA', 'Peugeot', '2008'),
('EUROPA', 'FRANÇA', 'Peugeot', '308'),
('EUROPA', 'FRANÇA', 'Peugeot', '408'),
('EUROPA', 'FRANÇA', 'Peugeot', '3008'),
('EUROPA', 'FRANÇA', 'Citroën', 'C3'),
('EUROPA', 'FRANÇA', 'Citroën', 'C4'),
('EUROPA', 'FRANÇA', 'Citroën', 'ë-C4'),
('EUROPA', 'FRANÇA', 'Citroën', 'C5 X'),
('EUROPA', 'FRANÇA', 'DS Automobiles', 'DS 3'),
('EUROPA', 'FRANÇA', 'DS Automobiles', 'DS 4'),
('EUROPA', 'FRANÇA', 'DS Automobiles', 'DS 7'),
('EUROPA', 'FRANÇA', 'DS Automobiles', 'DS 9'),

-- SUÉCIA
('EUROPA', 'SUÉCIA', 'Volvo', 'XC40'),
('EUROPA', 'SUÉCIA', 'Volvo', 'C40'),
('EUROPA', 'SUÉCIA', 'Volvo', 'EX30'),
('EUROPA', 'SUÉCIA', 'Volvo', 'EX90'),
('EUROPA', 'SUÉCIA', 'Volvo', 'XC60'),
('EUROPA', 'SUÉCIA', 'Polestar', 'Polestar 2'),
('EUROPA', 'SUÉCIA', 'Polestar', 'Polestar 3'),
('EUROPA', 'SUÉCIA', 'Polestar', 'Polestar 4'),
('EUROPA', 'SUÉCIA', 'Koenigsegg', 'One:1'),
('EUROPA', 'SUÉCIA', 'Koenigsegg', 'Gemera'),
('EUROPA', 'SUÉCIA', 'Koenigsegg', 'Agera'),
('EUROPA', 'SUÉCIA', 'Koenigsegg', 'CC850'),

-- REINO UNIDO
('EUROPA', 'REINO UNIDO', 'Jaguar', 'F-Type'),
('EUROPA', 'REINO UNIDO', 'Jaguar', 'F-Pace'),
('EUROPA', 'REINO UNIDO', 'Jaguar', 'E-Pace'),
('EUROPA', 'REINO UNIDO', 'Jaguar', 'I-Pace'),
('EUROPA', 'REINO UNIDO', 'Land Rover', 'Defender'),
('EUROPA', 'REINO UNIDO', 'Land Rover', 'Range Rover'),
('EUROPA', 'REINO UNIDO', 'Land Rover', 'Range Rover Sport'),
('EUROPA', 'REINO UNIDO', 'Land Rover', 'Evoque'),
('EUROPA', 'REINO UNIDO', 'Land Rover', 'Discovery Sport'),
('EUROPA', 'REINO UNIDO', 'Mini', 'Cooper'),
('EUROPA', 'REINO UNIDO', 'Mini', 'Countryman'),
('EUROPA', 'REINO UNIDO', 'Mini', 'Electric'),
('EUROPA', 'REINO UNIDO', 'Aston Martin', 'DB5'),
('EUROPA', 'REINO UNIDO', 'Aston Martin', 'DBX'),
('EUROPA', 'REINO UNIDO', 'Aston Martin', 'DB12'),
('EUROPA', 'REINO UNIDO', 'Aston Martin', 'Vantage'),
('EUROPA', 'REINO UNIDO', 'Aston Martin', 'Vanquish'),
('EUROPA', 'REINO UNIDO', 'Aston Martin', 'Valhalla'),
('EUROPA', 'REINO UNIDO', 'Aston Martin', 'Valkyrie'),
('EUROPA', 'REINO UNIDO', 'McLaren', '765LT'),
('EUROPA', 'REINO UNIDO', 'McLaren', '720S'),
('EUROPA', 'REINO UNIDO', 'McLaren', 'Artura'),
('EUROPA', 'REINO UNIDO', 'McLaren', '750S'),
('EUROPA', 'REINO UNIDO', 'McLaren', 'GT'),
('EUROPA', 'REINO UNIDO', 'McLaren', '570S'),
('EUROPA', 'REINO UNIDO', 'McLaren', 'P1'),
('EUROPA', 'REINO UNIDO', 'McLaren', 'Senna'),
('EUROPA', 'REINO UNIDO', 'McLaren', 'Speedtail'),
('EUROPA', 'REINO UNIDO', 'McLaren', 'W1'),

-- ESPANHA
('EUROPA', 'ESPANHA', 'Seat', 'Leon'),
('EUROPA', 'ESPANHA', 'Seat', 'Arona'),
('EUROPA', 'ESPANHA', 'Seat', 'Ateca'),
('EUROPA', 'ESPANHA', 'Cupra', 'Formentor'),
('EUROPA', 'ESPANHA', 'Cupra', 'Born'),
('EUROPA', 'ESPANHA', 'Cupra', 'Tavascan'),

-- CHECA
('EUROPA', 'CHECA', 'Skoda', 'Octavia'),
('EUROPA', 'CHECA', 'Skoda', 'Fabia'),
('EUROPA', 'CHECA', 'Skoda', 'Enyaq'),
('EUROPA', 'CHECA', 'Skoda', 'Kodiaq'),
('EUROPA', 'CHECA', 'Skoda', 'Superb'),

-- ROMÉNIA
('EUROPA', 'ROMÉNIA', 'Dacia', 'Sandero'),
('EUROPA', 'ROMÉNIA', 'Dacia', 'Logan'),
('EUROPA', 'ROMÉNIA', 'Dacia', 'Spring'),
('EUROPA', 'ROMÉNIA', 'Dacia', 'Duster'),

-- CROÁCIA
('EUROPA', 'CROÁCIA', 'Rimac', 'Nevera'),

-- AMÉRICA DO NORTE
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Ford', 'Focus'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Ford', 'Fiesta'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Ford', 'Puma'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Ford', 'Kuga'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Ford', 'Mustang Mach-E'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Ford', 'Mustang GT'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Tesla', 'Model 3'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Tesla', 'Model Y'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Tesla', 'Model S'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Tesla', 'Model X'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Chevrolet', 'Camaro'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Chevrolet', 'Corvette C8 Stingray'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Chevrolet', 'Corvette C1'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Chevrolet', 'Corvette C7'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Jeep', 'Renegade'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Jeep', 'Compass'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Jeep', 'Wrangler'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Jeep', 'Grand Cherokee'),
('AMÉRICA DO NORTE', 'ESTADOS UNIDOS', 'Cadillac', 'Escalade'),

-- ÁSIA
('ÁSIA', 'JAPÃO', 'Toyota', 'Supra MK4'),
('ÁSIA', 'JAPÃO', 'Toyota', 'Supra MK5'),
('ÁSIA', 'JAPÃO', 'Toyota', 'Corolla'),
('ÁSIA', 'JAPÃO', 'Toyota', 'Yaris'),
('ÁSIA', 'JAPÃO', 'Toyota', 'C-HR'),
('ÁSIA', 'JAPÃO', 'Toyota', 'RAV4'),
('ÁSIA', 'JAPÃO', 'Toyota', 'Aygo X'),
('ÁSIA', 'JAPÃO', 'Toyota', 'bZ4X'),
('ÁSIA', 'JAPÃO', 'Lexus', 'LFA'),
('ÁSIA', 'JAPÃO', 'Lexus', 'UX'),
('ÁSIA', 'JAPÃO', 'Lexus', 'NX'),
('ÁSIA', 'JAPÃO', 'Lexus', 'RX'),
('ÁSIA', 'JAPÃO', 'Lexus', 'RZ'),
('ÁSIA', 'JAPÃO', 'Honda', 'Civic'),
('ÁSIA', 'JAPÃO', 'Honda', 'Civic Type-R'),
('ÁSIA', 'JAPÃO', 'Honda', 'HR-V'),
('ÁSIA', 'JAPÃO', 'Honda', 'CR-V'),
('ÁSIA', 'JAPÃO', 'Honda', 'Jazz'),
('ÁSIA', 'JAPÃO', 'Honda', 'e:Ny1'),
('ÁSIA', 'JAPÃO', 'Mazda', 'Mazda 2'),
('ÁSIA', 'JAPÃO', 'Mazda', 'Mazda 3'),
('ÁSIA', 'JAPÃO', 'Mazda', 'CX-30'),
('ÁSIA', 'JAPÃO', 'Mazda', 'CX-5'),
('ÁSIA', 'JAPÃO', 'Mazda', 'MX-30'),
('ÁSIA', 'JAPÃO', 'Mazda', 'MX-5'),
('ÁSIA', 'JAPÃO', 'Mazda', 'MX-7'),
('ÁSIA', 'JAPÃO', 'Nissan', 'Qashqai'),
('ÁSIA', 'JAPÃO', 'Nissan', 'Juke'),
('ÁSIA', 'JAPÃO', 'Nissan', 'X-Trail'),
('ÁSIA', 'JAPÃO', 'Nissan', 'Leaf'),
('ÁSIA', 'JAPÃO', 'Nissan', 'Ariya'),
('ÁSIA', 'JAPÃO', 'Subaru', 'Impreza'),
('ÁSIA', 'JAPÃO', 'Subaru', 'XV'),
('ÁSIA', 'JAPÃO', 'Subaru', 'Outback'),
('ÁSIA', 'JAPÃO', 'Subaru', 'Solterra'),
('ÁSIA', 'JAPÃO', 'Suzuki', 'Swift'),
('ÁSIA', 'JAPÃO', 'Suzuki', 'Vitara'),
('ÁSIA', 'JAPÃO', 'Suzuki', 'S-Cross'),
('ÁSIA', 'COREIA DO SUL', 'Hyundai', 'i20'),
('ÁSIA', 'COREIA DO SUL', 'Hyundai', 'i30'),
('ÁSIA', 'COREIA DO SUL', 'Hyundai', 'Kona'),
('ÁSIA', 'COREIA DO SUL', 'Hyundai', 'Tucson'),
('ÁSIA', 'COREIA DO SUL', 'Hyundai', 'Ioniq 5'),
('ÁSIA', 'COREIA DO SUL', 'Hyundai', 'Ioniq 6'),
('ÁSIA', 'COREIA DO SUL', 'Kia', 'Ceed'),
('ÁSIA', 'COREIA DO SUL', 'Kia', 'Sportage'),
('ÁSIA', 'COREIA DO SUL', 'Kia', 'Niro'),
('ÁSIA', 'COREIA DO SUL', 'Kia', 'EV6'),
('ÁSIA', 'COREIA DO SUL', 'Kia', 'EV9'),
('ÁSIA', 'CHINA', 'MG', 'MG4'),
('ÁSIA', 'CHINA', 'MG', 'MG5'),
('ÁSIA', 'CHINA', 'MG', 'ZS EV'),
('ÁSIA', 'CHINA', 'MG', 'Marvel R'),
('ÁSIA', 'CHINA', 'BYD', 'Atto 3'),
('ÁSIA', 'CHINA', 'BYD', 'Dolphin'),
('ÁSIA', 'CHINA', 'BYD', 'Seal'),
('ÁSIA', 'CHINA', 'BYD', 'Tang');
